name: Cargo stable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    # Test with std and no_std
    strategy:
      matrix:
        flags:
          - ""
        # TODO: Enable no_std as well.
        # - "--no-default-features"
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: "cargo build --verbose ${{ matrix.flags }}"
      - run: "cargo test --verbose ${{ matrix.flags }}"

